language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
deploy:
  provider: heroku
  app: bobvince-discord
  api_key:
    secure: $HEROKU_AUTH_TOKEN
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL